Provide H5O_fsinfo_set_version declaration
To address:

/emsdk_portable/emscripten/sdk/emcc -D_GNU_SOURCE -IModules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/ZLIB/src -I/ITK/Modules/ThirdParty/HDF5/src -IModules/ThirdParty/HDF5/src -I/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src -IModules/ThirdParty/HDF5/src/itkhdf5 -std=c99 -Wno-warn-absolute-paths --memory-init-file 0 -s WASM=0 -lnodefs.js -Wno-almost-asm  -Wno-uninitialized -Wno-unused-parameter -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow  -w -DNDEBUG -O2 -fPIC   -std=gnu99 -MD -MT Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Fsuper.c.o -MF Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Fsuper.c.o.d -o Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeFiles/hdf5-static.dir/H5Fsuper.c.o   -c /ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fsuper.c
/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fsuper.c:1397:16: error: implicit declaration of function 'H5O__fsinfo_set_version' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            if(H5O__fsinfo_set_version(f, &fsinfo) < 0)