Fixed MSVC compile error in C++23 mode (#947)
Error message from MSVC with C++23 enabled:

error C2440: 'return': cannot convert from 'int' to 'std::basic_string<char,std::char_traits,std::allocator>'

Co-authored-by: Sean McBride <sean@rogue-research.com>