Use HDva_copy() and introduce a bunch of compatbility format-string constants for uppercase hexadecimal strings, `PRIX...`.  Should fix the VS2010 errors that Allen mentioned:
H5system.obj : error LNK2019: unresolved external symbol va_copy referenced in  function HDvasprintf                                                            [C:\autotest\hdf5trunk-StdShar-code-vs10\build\ctest\hdfbld\src\hdf5-shared.vcxproj]                                                                            2                                                                               ..\..\..\hdfsrc\test\h5test.c(2103): error C2146: syntax error : missing ')'    before identifier 'PRIX64'                                                      [C:\autotest\hdf5trunk-StdShar-code-vs10\build\ctest\hdfbld\test\hdf5_test-static.vcxproj]