Fix the CI build failures for undefined reference to `H5D_OBJ_ID' which was a macro defined in src/H5Dprivate.h. The header file "H5Dprivate.h" was removed from src/H5Gtraverse.c in the commit "Remove useless headers (#4145)".