Add h5test_wrapper.h to isolate gcc and g++ to compile _Float16 files on aarch64
_Float16 was supported in commit 330b80a266.

However there is build error report in aarch64, like this:
../../../src/H5private.h:605:23: error: '_Float16' does not name a type; did you mean '_Float64'?
  605 | __extension__ typedef _Float16 H5__Float16;
      |                       ^~~~~~~~
      |                       _Float64
make[2]: *** [Makefile:972: dsets.o] Error 1
make[1]: *** [Makefile:910: all-recursive] Error 1
make: *** [Makefile:739: all-recursive] Error 1

This commit adds a wrapper to isolate this difference

Signed-off-by: abushwang <abushwangs@gmail.com>